routes/web.php
    Route::post('login', 'Auth\LoginController@store')->name('store.admin');
    Route::get('logout', 'Auth\LoginController@logout')->name('logout.admin');
    Route::get('forgot', 'Auth\ForgotPasswordController@index')->name('forgot.admin');
    Route::get('reset-password/{token}', 'Auth\ForgotPasswordController@formForgot')->name('formRequest.admin');
    Route::put('forgot', 'Auth\ForgotPasswordController@sendMailWithToken')->name('sendMailWithToken.forgot.admin');
    Route::post('forgot/{token}', 'Auth\ForgotPasswordController@changePassword')->name('changePassword.forgot.admin');

    Route::group(['as' => 'admin.','middleware' => 'auth.admin',  'namespace' => 'Admin'], function () {
        // Route::get('/', function () {

        //     return view('admin.dashboard.index');
        // })->name('dashboard');
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::resource('/manage', 'AdminController')->middleware('check_role:supper_admin');
        Route::get('/manage-list', 'AdminController@list')->name('manage.list')->middleware('check_role:supper_admin');
        Route::post('/manage/avatar/{id}', 'AdminController@addAvatar')->name('manage.avatar')->middleware('check_role:supper_admin');
        Route::post('/manage-change/{id}', 'AdminController@changePassword')->name('manage.change')->middleware('check_role:supper_admin');

        /* Bộ môn */
        Route::resource('/bomon', 'BoMonController')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::get('/bomon-list', 'BoMonController@list')->name('bomon.list')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');

        /* Môn Học */
        Route::resource('/monhoc', 'MonHocController')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::get('/monhoc-list', 'MonHocController@list')->name('monhoc.list')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');

        /* Giáo viên */
        Route::resource('/giaovien', 'GiaoVienController')->middleware('check_role:supper_admin,admin,quan_ly');
        Route::get('/giaovien-list', 'GiaoVienController@list')->name('giaovien.list')->middleware('check_role:supper_admin,quan_ly');
        Route::get('/giaovien/excel/get', 'GiaoVienController@excel')->name('giaovien.excel')->middleware('check_role:supper_admin,quan_ly');

        /* Chức vụ */
        Route::resource('/chucvu', 'ChucVuController')->middleware('check_role:supper_admin,admin,quan_ly');
        Route::get('/chucvu-list', 'ChucVuController@list')->name('chucvu.list')->middleware('check_role:supper_admin,quan_ly');

        /* Hệ phai */
        Route::resource('/hephai', 'HePhaiController')->middleware('check_role:supper_admin,admin,quan_ly');
        Route::get('/hephai-list', 'HePhaiController@list')->name('hephai.list')->middleware('check_role:supper_admin,quan_ly');

        /* Lớp Học */
        Route::resource('/lophoc', 'LopHocController')->middleware('check_role:supper_admin,dao_tao,quan_ly');
        Route::get('/lophoc-list', 'LopHocController@list')->name('lophoc.list')->middleware('check_role:supper_admin,dao_tao,quan_ly');
        Route::post('/lophoc/filter', 'LopHocController@filter')->name('lophoc.filter')->middleware('check_role:supper_admin,dao_tao,quan_ly');
        Route::get('/lophoc/hocvien/add/{id}', 'LopHocController@create')->name('lophoc.hocvien.create')->middleware('check_role:supper_admin,dao_tao,quan_ly');
        Route::get('/lophoc/tkb/{id}', 'LopHocController@lopThoiKhoaBieu')->name('lophoc.tkb')->middleware('check_role:supper_admin,dao_tao,quan_ly');
        Route::get('/lophoc/tkb/list/{id}', 'LopHocController@listThoiKhoaBieu')->name('lophoc.tkb.list')->middleware('check_role:supper_admin,dao_tao,quan_ly');
        Route::get('/lophoc/diemdanh/list', 'LopHocController@listLopDiemDanh')->name('lophoc.diemdanh')->middleware('check_role:supper_admin,quan_ly,hanh_chinh,dao_tao');
        Route::get('/lophoc/{id}/diemdanh/create', 'LopHocController@lophocDiemDanh')->name('lophoc.diemdanh.create')->middleware('check_role:supper_admin,quan_ly,hanh_chinh,dao_tao');
        Route::get('/lophoc/{id}/diemdanh/create/ngay', 'LopHocController@lophocDiemDanhDetail')->name('lophoc.diemdanh.create.detail')->middleware('check_role:supper_admin,quan_ly,hanh_chinh,dao_tao');
        Route::post('/lophoc/list/diemdanh', 'LopHocController@listDiemDanh')->name('lophoc.diemdanh.list')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::get('/lophoc/diemdanh/show/{id}/{lophoc}', 'LopHocController@showDiemDanh')->name('lophoc.diemdanh.show')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::get('/lophoc/diem/list', 'LopHocController@listLopDiem')->name('lophoc.diem')->middleware('check_role:supper_admin,quan_ly');
        Route::post('/lophoc/diem/store', 'LopHocController@storeDiem')->name('lophoc.diem.store')->middleware('check_role:supper_admin,quan_ly');
        Route::get('/lophoc/diem/create/{id}', 'LopHocController@lopHocDiem')->name('lophoc.diem.create')->middleware('check_role:supper_admin,quan_ly');

        Route::post('/lophoc/diem/lydo', 'LopHocController@monHocDiemLyDo')->name('lophoc.diem.lydo')->middleware('check_role:supper_admin,quan_ly');
        Route::post('/lophoc/monhoc/diemdanh', 'LopHocController@monHocDiemDanhPost')->name('lophoc.monhoc.diemdanh.post')->middleware('check_role:supper_admin,quan_ly');
        Route::post('/lophoc/monhoc/{id}', 'LopHocController@lopMonHoc')->name('lophoc.monhoc')->middleware('check_role:supper_admin,quan_ly');
        Route::post('/lophoc/hocvien/{id}', 'LopHocController@lopHocVien')->name('lophoc.hocvien')->middleware('check_role:supper_admin,quan_ly');
        Route::get('/lophoc/json/{id}', 'LopHocController@editJson')->name('lophoc.json')->middleware('check_role:supper_admin,quan_ly');
        Route::get('/lophoc/all/export', 'LopHocController@export')->name('lophoc.export')->middleware('check_role:supper_admin,quan_ly');
        Route::get('/lophoc/export/{id}', 'LopHocController@exportDetail')->name('lophoc.export.detail')->middleware('check_role:supper_admin,quan_ly');

        /* Lớp Học */
        Route::resource('/lydo', 'LyDoDiemController')->middleware('check_role:supper_admin,dao_tao,quan_ly');
        Route::get('/lydo-list', 'LyDoDiemController@list')->name('lydo.list')->middleware('check_role:supper_admin,dao_tao,quan_ly');

        /* Thời khoá biểu */
        Route::resource('/thoi-khoa-bieu', 'ThoiKhoaBieuController')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::post('/thoi-khoa-bieu/lop-mon-hoc', 'ThoiKhoaBieuController@lopMonHoc')->name('thoi-khoa-bieu.lopmonhoc')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::get('/thoi-khoa-bieu/index/{lophoc}', 'ThoiKhoaBieuController@index')->name('thoi-khoa-bieu.index')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::get('/thoi-khoa-bieu/all/lophoc', 'ThoiKhoaBieuController@indexLopHoc')->name('thoi-khoa-bieu.all.lophoc')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::post('/thoi-khoa-bieu/get/lophoc', 'ThoiKhoaBieuController@lopHoc')->name('thoi-khoa-bieu.lophoc')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');

        /* Học Viên */
        Route::resource('/hoc-vien', 'HocVienController')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien-list', 'HocVienController@list')->name('hoc-vien.list')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien/list2', 'HocVienController@listCalander')->name('hoc-vien.list.calandar')->middleware('check_role:supper_admin');
        Route::post('/hoc-vien/import', 'HocVienController@import')->name('hoc-vien.import')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien/all/export', 'HocVienController@export')->name('hoc-vien.export')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        
        /* chỉnh sửa lại route view import học viên */
        Route::get('/hv-import', 'HocVienController@importView')->name('hoc-vien.importView')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        /* ------------------- */

        Route::get('/hoc-vien/theodoiyte/{id}', 'HocVienController@theoDoiYTe')->name('hoc-vien.theo-doi-y-te')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien/vephep/{id}', 'HocVienController@vePhep')->name('hoc-vien.ve-phep')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
       
        Route::get('/hoc-vien/taichinh/filter/{id}', 'HocVienController@filterTaiChinh')->name('hoc-vien.taichinh.filter')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien/anhquatrinh/{id}', 'HocVienController@indexAnhQuaTrinh')->name('hoc-vien.anhquatrinh.index')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::post('/hoc-vien/anhquatrinh', 'HocVienController@themAnhQuaTrinh')->name('hoc-vien.anhquatrinh.post')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien/diem/export/{id}', 'HocVienController@exportDiem')->name('hoc-vien.diem.export')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien/diemdanh/export/{id}', 'HocVienController@exportDiemDanh')->name('hoc-vien.diemdanh.export')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');

        /* Về phép */
        Route::resource('ve-phep', 'VePhepController')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/ve-phep-list/{id}', 'VePhepController@list')->name('ve-phep.list')->middleware('check_role:supper_admin,hanh_chinh,quan_ly');

        /* Phòng */

app/Models/HocVien.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use DB;
use Carbon\Carbon;
class HocVien extends Model
{
    // use SoftDeletes;
    
    const CHUA_SU_DUNG = 0;
    const DA_SU_DUNG = 1;

    protected $table = 'hoc_viens';

    protected $fillable = [
        'nguoi_bao_ho_id', 
        'ma_hoc_vien', 
        'ten',
        'dia_chi', 
        'ngay_sinh', 
        'gioi_tinh',
        'ngay_vao',
        'ngay_tot_nghiep',
        'so_cmnd',
        'ngay_cap_cmnd', 
        'noi_cap_cmnd', 
        'trinh_do_van_hoa',
        'hon_nhan', 
        'vo_chong',
        'con_1',
        'con_2',
        'nghe_nghiep', 
        'tinh_trang',
        'tien_an', 
        've_toi_tien_an', 
        'tien_su',
        've_toi_tien_su', 
        'ma_tuy_su_dung', 
        'hinh_thuc_su_dung',
        'tien_su_benh_ly', 
        'chieu_cao', 
        'can_nang',
        'avatar_url',
        'tai_chinh_con_lai',
        'import',
    ];

    public function kyluat()
    {
        return $this->hasOne('App\Models\KyLuat');
    }

    public function vephep()
    {
        return $this->hasOne('App\Models\VePhep');
    }

    public function khamsuckhoe()
    {
        return $this->hasOne('App\Models\KhamSucKhoe');
    }
    
    public function tinhtrangnghien()
    {
        return $this->hasOne('App\Models\TinhTrangNghien');
    }

    public function truongnhom()
    {
        return $this->hasOne('App\Models\Nhom','truong_nhom_id');
    }

    public function truongphong()
    {
        return $this->hasOne('App\Models\Phong','ten_truong_phong');
    }
    
    public function nguoibaoho()
    {
        return $this->belongsTo('App\Models\NguoiBaoHo','nguoi_bao_ho_id');
    }

    public function trungtam()
    {
        return $this->hasOne('App\Models\TrungTam');
    }

    public function ngayhocvien()
    {
        return $this->hasMany('App\Models\NgayHocVien');
    }

    public function anhhocvien()
    {
        return $this->hasMany(AnhHocVien::class, 'hoc_vien_id');
    }

    public function anhquatrinh()
    {
        return $this->hasMany(AnhQuaTrinh::class, 'hoc_vien_id');
    }

    public function phong()
    {
        return $this->belongsToMany('App\Models\Phong','phong_hoc_viens')->withPivot('ly_do','type')->withTimestamps();
    } 

    public function taichinh()
    {
        return $this->hasMany('App\Models\TaiChinh');
    }

    public function hanhkiem()
    {
        return $this->hasOne('App\Models\HanhKiem');
    }

    public function nhom()
    {
        return $this->belongsToMany('App\Models\Nhom','nhom_hoc_vien')->withTimestamps();
    }

    public function sukien()
    {
        return $this->belongsToMany('App\Models\SuKien','su_kien_hoc_vien');
    }

    public function lophoc()
    {
        return $this->belongsToMany('App\Models\LopHoc','lop_hoc_hoc_vien');
    } 


    public function diemdanh()
    {
        return $this->belongstoMany('App\Models\LopHoc','diem_danh_lop_hocs')->withTimestamps()->withPivot('ca_hoc','ngay','created_at');
    } 

    public function diem_monhoc()
    {
        return $this->belongstoMany('App\Models\LopHoc','diem_mon_hocs')->withPivot('diem', 'ly_do_id')->withTimestamps();
    } 

    public function huongnghiep()
    {
        return $this->belongsToMany('App\Models\HuongNghiep','huong_nghiep_hoc_vien')->withTimestamps();
    }

    public function checkNotDiemDanh($ngay,$lop_hoc_id,$ca_hoc){
        return DB::table('diem_danh_lop_hocs')
        ->Leftjoin('lop_hocs', 'diem_danh_lop_hocs.lop_hoc_id', '=', 'lop_hocs.id')
        ->Leftjoin('hoc_viens', 'diem_danh_lop_hocs.hoc_vien_id', '=', 'hoc_viens.id')
        ->select('diem_danh_lop_hocs.*')
        ->where('diem_danh_lop_hocs.ngay',$ngay)
        ->where('diem_danh_lop_hocs.lop_hoc_id',$lop_hoc_id)
        ->where('diem_danh_lop_hocs.ca_hoc',$ca_hoc)
        ->first();
    }

}

app/Http/Controllers/NguoiNha/ReportController.php
<?php

namespace App\Http\Controllers\NguoiNha;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\User\ReportRequest;
use App\Http\Models\Report;
use Auth;

class ReportController extends Controller
{

    public function index()
    {
        return view('nguoinha.hocvien.report-hv');
    }

    public function store(ReportRequest $request)
    {
        $data = $request->only([
            'content',
            'category_report',
        ]);
        $nguoibaoho = Auth::guard('nguoibaoho')->user();

        $report = $nguoibaoho->reports()->create($data);

        return redirect()->route('nguoibaoho.home');
    }
}

resources/views/nguoinha/hocvien/change-password.blade.php
@extends('nguoinha.layouts.index')
@section('content')
<div class="content-header mb-4 bg-white">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <h5 class="m-0 text-dark">Hồ sơ cá nhân</h5>
            </div>
            <!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Hồ sơ cá nhân</a></li>
                    <li class="breadcrumb-item active">Dashboard v1</li>
                </ol>

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /.content-header -->
    <section class="content">
      <div class="row">
      <div class="col-md-10 offset-md-1">
        <!-- Profile Image -->
        <div class="card card-primary card-outline">
          <div class="card-body box-profile">
            <div class="text-center">
              <img class="profile-user-img img-fluid img-circle" src="../../dist/img/user4-128x128.jpg" alt="User profile picture">
            </div>
            <h3 class="profile-username text-center">Nina Mcintire</h3>
            <p class="text-muted text-center">abc@gmail.com</p>

            <ul class="list-group list-group-unbordered mb-3">
              <li class="list-group-item">
                <b>Chức vụ</b> <a class="float-right">Supper admin</a>
              </li>
              <li class="list-group-item">
                <b>Giới tính</b> <a class="float-right">Nam</a>
              </li>
            </ul>
            <a href="#" class="btn btn-info btn-block update_pass"><b>Thay đổi mật khẩu</b></a>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
        </div>  
      </div>
    </section>

    <div class="mess-data"
      data-url-edit="{{ route('admin.manage.edit', 'ID_REPLY_IN_URL') }}"
    >
    </div>

    @component('admin.components.modals.edit-modal')
        @slot('title')
          Thay đổi mật khẩu
        @endslot
        @slot('form')
            <form 
                action="{{ route('admin.manage.store') }}" 
                id="update_pass" 
                role="form" 
                method="post"
                data-url-index="{{ route('admin.manage.index') }}">
                @csrf
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Mật khẩu cũ<span class="text-danger">*</span></label>
                                <input type="password" name="" class="form-control">
                                <span class="text-danger" role="alert"></span>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Mật khẩu mới<span class="text-danger">*</span></label>
                                <input type="password" name="" class="form-control">
                                <span class="text-danger" role="alert"></span>
                            </div>
                        </div>  
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Xác nhận khẩu mới<span class="text-danger">*</span></label>
                                <input type="password" name="" class="form-control">
                                <span class="text-danger" role="alert"></span>
                            </div>
                        </div>
                    </div>
                   <!-- end row -->
                </div>
                <div class="card-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times"></i> Hủy bỏ</button>
                    <button type="button" id="create_admin" class="btn btn-success float-right"><i class="fas fa-save"></i> Cập nhật mật khẩu</button>
                </div>
            </form>
        @endslot
    @endcomponent
@endsection
@section('scripts')
    <script>
      // update form modal
      $('body').on('click', '.update_pass', function(event) {
          event.preventDefault();
          $('#modal-edit').modal('show', { backdrop: 'true' });
      });
    </script>
@endsection

resources/views/nguoinha/hocvien/index.blade.php
@extends('nguoinha.layouts.index')
<style>
    .modal-body{
        padding: 0 !important;
    }
</style>
@section('content')
<div class="content-header mb-4 bg-white">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <h5 class="m-0 text-dark">Hồ sơ cá nhân</h5>
            </div>
            <!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
                    <li class="breadcrumb-item active">Hồ sơ cá nhân</li>
                </ol>

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">

                <!-- Profile Image -->
                <div class="card card-info card-outline">
                    <div class="card-body box-profile">
                        <div class="text-center">
                            @if(Auth::user()->hocvien->avatar_url == null)
                                <img class="profile-user-img img-fluid img-circle user_avatar" src="/admin_assets/images/logo/logo-aq-h.png" alt="User profile picture">
                            @else
                                <img class="profile-user-img img-fluid img-circle user_avatar" src="/storage/uploads/user_avatar/icon128/{{Auth::user()->hocvien->avatar_url}}" alt="User profile picture">
                            @endif
                        </div>

                        <h3 class="profile-username text-center">{{ Auth::user()->hocvien->ten }}<i class="far fa-check-circle text-success ml-2"></i></h3>

                        <p class="text-muted text-center">Học viên</p>

                        <ul class="list-group list-group-unbordered mb-3">
                            <li class="list-group-item">
                                <b>Email</b> <a class="float-right">{{ Auth::user()->email }}</a>
                            </li>
                            <li class="list-group-item">
                                <b>Số điện thoại</b> <a class="float-right">{{ Auth::user()->so_dien_thoai }}</a>
                            </li>
                            <!-- <li class="list-group-item">
                            <b>Tình trạng nghiện</b> <a class="float-right">{{ Auth::user()->hocvien->tinh_trang }}</a>
                            </li> -->
                        </ul>

                        <a href="#" class="btn btn-outline-info btn-block update_pass"><i class="far fa-lock"></i> Thay đổi mật khẩu</a>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-info card-outline">
                    <div class="card-header p-4">
                        <h5 class="mb-0">Thông tin học viên</h5>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="ttcn ml-2">
                                    <div class="d-flex mb-2">
                                        <span>Họ và tên: </span>
                                        <span class="ml-3"><strong>{{ Auth::user()->hocvien->ten }}</strong></span>
                                    </div>
                                    <div class="d-flex mb-2">
                                        <span>Mã học viên: </span>
                                        <span class="ml-3"><strong>{{ Auth::user()->hocvien->ma_hoc_vien }}</strong></span>
                                    </div>
                                    <div class="d-flex mb-2">
                                        <span>Gioi tinh: </span>
                                        <span class="ml-3"><strong>Nam</strong></span>
                                    </div>
                                    <div class="d-flex mb-2">
                                        <span>Tình trạng: </span>
                                        <span class="ml-3"><strong>{{ Auth::user()->hocvien->tinh_trang }}</strong></span>
                                    </div>
                                </div>
                                @foreach ( Auth::user()->hocvien->hanhkiem()->get() as $item)
                                    <div class="ttcn ml-5">
                                        <p>Hạnh kiểm :  {{$item->ten_hanh_kiem}} - Ngày Xét : {{$item->created_at}}</p>
                                    </div>
                                @endforeach

                                @foreach ( Auth::user()->hocvien->kyluat()->get() as $item)
                                    <div class="ttcn ml-5">
                                        <p>kỷ luật :  {{$item->ly_do}} - Ghi chú : {{$item->ghi_chu}} - Ngày Xét : {{$item->created_at}}</p>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.nav-tabs-custom -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
</section>
@component('admin.components.modals.edit-modal')
        @slot('title')
          Thay đổi mật khẩu
        @endslot
        @slot('form')
            <form 
                class="mb-0"
                action="{{ route('admin.manage.store') }}" 
                id="update_pass" 
                role="form" 
                method="post"
                data-url-index="{{ route('admin.manage.index') }}">
                @csrf
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Mật khẩu cũ <span class="text-danger">*</span></label>
                                <input type="password" name="" class="form-control">
                                <span class="text-danger" role="alert"></span>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Mật khẩu mới <span class="text-danger">*</span></label>
                                <input type="password" name="" class="form-control">
                                <span class="text-danger" role="alert"></span>
                            </div>
                        </div>  
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Xác nhận khẩu mới <span class="text-danger">*</span></label>
                                <input type="password" name="" class="form-control">
                                <span class="text-danger" role="alert"></span>
                            </div>
                        </div>
                    </div>
                   <!-- end row -->
                </div>
                <div class="card-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times"></i> Hủy bỏ</button>
                    <button type="button" id="create_admin" class="btn btn-success float-right"><i class="fas fa-save"></i> Cập nhật mật khẩu</button>
                </div>
            </form>
        @endslot
    @endcomponent
@endsection
@section('scripts')
    <script>
      // update form modal
      $('body').on('click', '.update_pass', function(event) {
          event.preventDefault();
          $('#modal-edit').modal('show', { backdrop: 'true' });
      });
    </script>
@endsection

resources/views/nguoinha/hocvien/report-hv.blade.php
@extends('nguoinha.layouts.index')
@section('content')
<div class="content-header mb-4 bg-white">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <h5 class="m-0 text-dark">Gửi khiếu nại</h5>
            </div>
            <!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">Hồ sơ cá nhân</li>
                    <li class="breadcrumb-item active"><a href="#">Khiếu nại</a></li>
                </ol>

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title">Form report học viên</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{ route('nguoibaoho.submitReport') }}" method="post">
                @csrf
                <div class="card-body">
                  <div class="form-group">
                    <label >Vấn đề khiếu nại</label>
                    <select class="form-control" name="category_report">
                      <option value="">Vui lòng chọn vấn đề khiếu nại</option>
                      @foreach (Config::get('admin.category_report') as $key => $category)
                        <option value="{{ $category['val'] }}">{{ $category['text'] }}</option>
                      @endforeach
                    </select>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1">Nội dung</label>
                    <textarea name="content" id="report_content" class="form-control" rows="4" placeholder="Enter ..."></textarea>
                  </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-info">Gửi khiếu nại</button>
                </div>
              </form>
          </div>
          <!-- .card -->
        </div>
        <!-- .col -->
      </div>
      <!-- /.row -->
    </div>
</section>
@endsection
@section('scripts')
    <script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
    <script>
    
    </script>
@endsection