routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
$host = env('APP_HOST');

/* admin route */

Route::domain(env('ADMIN_SUB_DOMAIN') . '.' . $host)->group(function () {
    Route::get('login', 'Auth\LoginController@index')->name('login.admin');
    Route::post('login', 'Auth\LoginController@store')->name('store.admin');
    Route::get('logout', 'Auth\LoginController@logout')->name('logout.admin');
    Route::get('forgot', 'Auth\ForgotPasswordController@index')->name('forgot.admin');
    Route::get('reset-password/{token}', 'Auth\ForgotPasswordController@formForgot')->name('formRequest.admin');
    Route::put('forgot', 'Auth\ForgotPasswordController@sendMailWithToken')->name('sendMailWithToken.forgot.admin');
    Route::post('forgot/{token}', 'Auth\ForgotPasswordController@changePassword')->name('changePassword.forgot.admin');

    Route::group(['as' => 'admin.','middleware' => 'auth.admin',  'namespace' => 'Admin'], function () {
        // Route::get('/', function () {

        //     return view('admin.dashboard.index');
        // })->name('dashboard');
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::resource('/manage', 'AdminController')->middleware('check_role:supper_admin');
        Route::get('/manage-list', 'AdminController@list')->name('manage.list')->middleware('check_role:supper_admin');
        Route::post('/manage/avatar/{id}', 'AdminController@addAvatar')->name('manage.avatar')->middleware('check_role:supper_admin');
        Route::post('/manage-change/{id}', 'AdminController@changePassword')->name('manage.change')->middleware('check_role:supper_admin');

        /* Bộ môn */
        Route::resource('/bomon', 'BoMonController')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::get('/bomon-list', 'BoMonController@list')->name('bomon.list')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');

        /* Môn Học */
        Route::resource('/monhoc', 'MonHocController')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::get('/monhoc-list', 'MonHocController@list')->name('monhoc.list')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');

        /* Giáo viên */
        Route::resource('/giaovien', 'GiaoVienController')->middleware('check_role:supper_admin,admin,quan_ly');
        Route::get('/giaovien-list', 'GiaoVienController@list')->name('giaovien.list')->middleware('check_role:supper_admin,quan_ly');
        Route::get('/giaovien/excel/get', 'GiaoVienController@excel')->name('giaovien.excel')->middleware('check_role:supper_admin,quan_ly');

        /* Chức vụ */
        Route::resource('/chucvu', 'ChucVuController')->middleware('check_role:supper_admin,admin,quan_ly');
        Route::get('/chucvu-list', 'ChucVuController@list')->name('chucvu.list')->middleware('check_role:supper_admin,quan_ly');

        /* Hệ phai */
        Route::resource('/hephai', 'HePhaiController')->middleware('check_role:supper_admin,admin,quan_ly');
        Route::get('/hephai-list', 'HePhaiController@list')->name('hephai.list')->middleware('check_role:supper_admin,quan_ly');

        /* Lớp Học */
        Route::resource('/lophoc', 'LopHocController')->middleware('check_role:supper_admin,dao_tao,quan_ly');
        Route::get('/lophoc-list', 'LopHocController@list')->name('lophoc.list')->middleware('check_role:supper_admin,dao_tao,quan_ly');
        Route::post('/lophoc/filter', 'LopHocController@filter')->name('lophoc.filter')->middleware('check_role:supper_admin,dao_tao,quan_ly');
        Route::get('/lophoc/hocvien/add/{id}', 'LopHocController@create')->name('lophoc.hocvien.create')->middleware('check_role:supper_admin,dao_tao,quan_ly');
        Route::get('/lophoc/tkb/{id}', 'LopHocController@lopThoiKhoaBieu')->name('lophoc.tkb')->middleware('check_role:supper_admin,dao_tao,quan_ly');
        Route::get('/lophoc/tkb/list/{id}', 'LopHocController@listThoiKhoaBieu')->name('lophoc.tkb.list')->middleware('check_role:supper_admin,dao_tao,quan_ly');
        Route::get('/lophoc/diemdanh/list', 'LopHocController@listLopDiemDanh')->name('lophoc.diemdanh')->middleware('check_role:supper_admin,quan_ly,hanh_chinh,dao_tao');
        Route::get('/lophoc/{id}/diemdanh/create', 'LopHocController@lophocDiemDanh')->name('lophoc.diemdanh.create')->middleware('check_role:supper_admin,quan_ly,hanh_chinh,dao_tao');
        Route::get('/lophoc/{id}/diemdanh/create/ngay', 'LopHocController@lophocDiemDanhDetail')->name('lophoc.diemdanh.create.detail')->middleware('check_role:supper_admin,quan_ly,hanh_chinh,dao_tao');
        Route::post('/lophoc/list/diemdanh', 'LopHocController@listDiemDanh')->name('lophoc.diemdanh.list')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::get('/lophoc/diemdanh/show/{id}/{lophoc}', 'LopHocController@showDiemDanh')->name('lophoc.diemdanh.show')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::get('/lophoc/diem/list', 'LopHocController@listLopDiem')->name('lophoc.diem')->middleware('check_role:supper_admin,quan_ly');
        Route::post('/lophoc/diem/store', 'LopHocController@storeDiem')->name('lophoc.diem.store')->middleware('check_role:supper_admin,quan_ly');
        Route::get('/lophoc/diem/create/{id}', 'LopHocController@lopHocDiem')->name('lophoc.diem.create')->middleware('check_role:supper_admin,quan_ly');

        Route::post('/lophoc/diem/lydo', 'LopHocController@monHocDiemLyDo')->name('lophoc.diem.lydo')->middleware('check_role:supper_admin,quan_ly');
        Route::post('/lophoc/monhoc/diemdanh', 'LopHocController@monHocDiemDanhPost')->name('lophoc.monhoc.diemdanh.post')->middleware('check_role:supper_admin,quan_ly');
        Route::post('/lophoc/monhoc/{id}', 'LopHocController@lopMonHoc')->name('lophoc.monhoc')->middleware('check_role:supper_admin,quan_ly');
        Route::post('/lophoc/hocvien/{id}', 'LopHocController@lopHocVien')->name('lophoc.hocvien')->middleware('check_role:supper_admin,quan_ly');
        Route::get('/lophoc/json/{id}', 'LopHocController@editJson')->name('lophoc.json')->middleware('check_role:supper_admin,quan_ly');
        Route::get('/lophoc/all/export', 'LopHocController@export')->name('lophoc.export')->middleware('check_role:supper_admin,quan_ly');
        Route::get('/lophoc/export/{id}', 'LopHocController@exportDetail')->name('lophoc.export.detail')->middleware('check_role:supper_admin,quan_ly');

        /* Lớp Học */
        Route::resource('/lydo', 'LyDoDiemController')->middleware('check_role:supper_admin,dao_tao,quan_ly');
        Route::get('/lydo-list', 'LyDoDiemController@list')->name('lydo.list')->middleware('check_role:supper_admin,dao_tao,quan_ly');

        /* Thời khoá biểu */
        Route::resource('/thoi-khoa-bieu', 'ThoiKhoaBieuController')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::post('/thoi-khoa-bieu/lop-mon-hoc', 'ThoiKhoaBieuController@lopMonHoc')->name('thoi-khoa-bieu.lopmonhoc')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::get('/thoi-khoa-bieu/index/{lophoc}', 'ThoiKhoaBieuController@index')->name('thoi-khoa-bieu.index')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::get('/thoi-khoa-bieu/all/lophoc', 'ThoiKhoaBieuController@indexLopHoc')->name('thoi-khoa-bieu.all.lophoc')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::post('/thoi-khoa-bieu/get/lophoc', 'ThoiKhoaBieuController@lopHoc')->name('thoi-khoa-bieu.lophoc')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');

        /* Học Viên */
        Route::resource('/hoc-vien', 'HocVienController')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien-list', 'HocVienController@list')->name('hoc-vien.list')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien/list2', 'HocVienController@listCalander')->name('hoc-vien.list.calandar')->middleware('check_role:supper_admin');
        Route::post('/hoc-vien/import', 'HocVienController@import')->name('hoc-vien.import')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien/all/export', 'HocVienController@export')->name('hoc-vien.export')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        
        /* chỉnh sửa lại route view import học viên */
        Route::get('/hv-import', 'HocVienController@importView')->name('hoc-vien.importView')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        /* ------------------- */

        Route::get('/hoc-vien/theodoiyte/{id}', 'HocVienController@theoDoiYTe')->name('hoc-vien.theo-doi-y-te')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien/vephep/{id}', 'HocVienController@vePhep')->name('hoc-vien.ve-phep')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
       
        Route::get('/hoc-vien/taichinh/filter/{id}', 'HocVienController@filterTaiChinh')->name('hoc-vien.taichinh.filter')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien/anhquatrinh/{id}', 'HocVienController@indexAnhQuaTrinh')->name('hoc-vien.anhquatrinh.index')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::post('/hoc-vien/anhquatrinh', 'HocVienController@themAnhQuaTrinh')->name('hoc-vien.anhquatrinh.post')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien/diem/export/{id}', 'HocVienController@exportDiem')->name('hoc-vien.diem.export')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');

app/Models/BoMon.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BoMon extends Model
{
    
    protected $table = 'bo_mons';

    protected $fillable = [
        'ten_bo_mon', 
    ];

    public function monhoc()
    {
        return $this->hasMany('App\Models\MonHoc');
    } 
}

app/Http/Controllers/Admin/BoMonController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\Admin\BoMonService;
use App\Http\Requests\Admin\BoMonRequest;
use Exception;
use Session;

class BoMonController extends Controller
{

    protected $bomonService;

    public function __construct(BoMonService $bomonService)
    {
        $this->bomonService = $bomonService;
    }

    /**
     * Display a listing of the resource.
     *m
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
    
        return view('admin.bomon.index');        
       
    }

    public function list(Request $request)
    {
        $listBoMon = $this->bomonService->getListBoMon($request->all());
        return $listBoMon;
    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BoMonRequest $request)
    {
        $result = $this->bomonService->store($request);

        if ($result) {
            Session::flash('message', trans('Thêm thành công ! '));
            return response()->json([
                'status' => true,
            ]);
        }

        Session::flash('error', trans('Thêm thất bại !'));
        return response()->json([
            'status' => false,
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $bomon = $this->bomonService->find($id);
        return view('admin.bomon.edit',compact('bomon'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(BoMonRequest $request, $id)
    {
        $result = $this->bomonService->update($request->all(),$id);

        if ($result) {
            Session::flash('message', trans('Thêm thành công ! '));
            return response()->json([
                'status' => true,
            ]);
            // return redirect()->route('admin.bomon.index');
        }

        Session::flash('error', trans('Thêm thất bại !'));
        return response()->json([
            'status' => false,
        ]);
        // return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $this->bomonService->delete($id);
            return redirect()->route('admin.bomon.index')->with('message', 'Xóa thành công');
        }catch (Exception $e) {
            report($e);
            return redirect()->route('admin.bomon.index')->with('error', 'Xóa không thành công');
        }
    }
}

resources/views/admin/bomon/edit.blade.php
@extends('admin.layouts.index')
@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-lg-12 mb-3">
                    <h1>Sửa Bộ Môn</h1>
                </div>
                <div class="col-lg-12">
                    <a  href="{{ URL::previous() }}" class="btn btn-default"><i class="fas fa-undo"></i> Trở về</a>
                </div>
                <!-- ./col -->
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <section class="content">
        <div class="row">
            <div class="col-8">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Block Buttons</h3>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('admin.bomon.update',$bomon->id)}}"  role="form" method="post">
                            @csrf
                            <input name="_method" type="hidden" value="PUT">
                            <div class="card-body">
                                <div class="form-group">
                                    <label>Tên bộ môn</label>
                                    <input type="text" name="ten_bo_mon" value="{{$bomon->ten_bo_mon}}" class="form-control" id="exampleInputEmail1" placeholder="Tên Bộ Môn">
                                    <span class="text-danger ten_bo_mon" role="alert"></span>
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Hủy bỏ</button>
                                <button type="submit" class="btn btn-primary float-right">Lưu</button>
                            </div>
                        </form>
                    </div>
                </div>
                
            </div>
        </div>
    </section>
@endsection

resources/views/admin/bomon/index.blade.php
@extends('admin.layouts.index')
@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h4>Danh sách bộ môn </h4>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active"> Bộ môn</li>
                    </ol>
                </div> 
                <div class="col-12 mt-2">
                    <a href="javascript:void(0)" class="btn btn-success" data-toggle="modal" data-target="#modal-default">
                        <i class="fas fa-plus"></i> Thêm bộ môn
                    </a>
                </div>
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content-header -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h3 class="card-title flex-grow-1"><i class="fas fa-th"></i> Danh sách bộ môn</h3>
                    </div>
                    <div class="card-body">
                        <div id="table_wrapper" class="table-responsive-sm">
                            <table id="table_bm" class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>Stt</th>
                                        <th>Bộ môn</th>
                                        <th>Tác vụ</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>                  
            </div>
        </div>
        {{ Form::open(['route' => ['admin.bomon.destroy', 'ID_REPLY_IN_URL'], 'id' => 'delete-bomon-form', 'class' => 'form-horizontal']) }}
            {{ method_field('DELETE') }}
        {{ Form::close() }}      
    </section>

    <div class="mess-data"
        data-url-datatable="{{ route('admin.bomon.list') }}"
        data-url-edit="{{ route('admin.bomon.edit', 'ID_REPLY_IN_URL') }}"
        data-url-update="{{ route('admin.bomon.update', 'ID_REPLY_IN_URL') }}"
        data-url-delete="{{ route('admin.bomon.destroy', 'ID_REPLY_IN_URL') }}">
    </div>

    @component('admin.components.modals.alert-delete')
        @slot('headerText')
            {{ "Bạn có muốn xóa bộ môn này không ?" }}
        @endslot
    @endcomponent

    @component('admin.components.modals.form-modal')
        @slot('class')
            cus_modal
        @endslot
        @slot('title')
            Thêm mới bộ môn
        @endslot
        @slot('form')
            <form action="{{ route('admin.bomon.store') }}" id="create_bomon" role="form" method="post" data-url-index="{{ route('admin.bomon.index') }}">
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label>Tên bộ môn</label>
                        <input type="text" name="ten_bo_mon" class="form-control text-capitalize" placeholder="Tên bộ môn">
                        <span class="text-danger ten_bo_mon" role="alert"></span>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times"></i> Hủy bỏ</button>
                    <button type="submit" class="btn btn-success float-right"><i class="far fa-save"></i> Lưu thông tin</button>
                </div>
            </form>
        @endslot
    @endcomponent

    @component('admin.components.modals.edit-modal')
        @slot('title')
            Chỉnh sửa bộ môn
        @endslot
        @slot('form')
        <form action="" id="update_bomon" role="form" method="POST" data-url-index="{{ route('admin.bomon.index') }}">
                @csrf
                <input name="_method" type="hidden" value="PUT"> 
                <div class="card-body">
                    <div class="form-group">
                        <label>Tên bộ môn</label>
                        <input type="text" name="ten_bo_mon" class="form-control text-capitalize" placeholder="Tên bộ môn">
                        <span class="text-danger ten_bo_mon" role="alert"></span>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times"></i> Hủy bỏ</button>
                    <button type="submit" class="btn btn-success float-right"><i class="far fa-save"></i> Lưu thông tin</button>
                </div>
            </form>
        @endslot
    @endcomponent

@endsection
@section('scripts')
    {{ Html::script(mix('admin/bomon.js')) }}
@endsection