routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
$host = env('APP_HOST');

/* admin route */

Route::domain(env('ADMIN_SUB_DOMAIN') . '.' . $host)->group(function () {
    Route::get('login', 'Auth\LoginController@index')->name('login.admin');
    Route::post('login', 'Auth\LoginController@store')->name('store.admin');
    Route::get('logout', 'Auth\LoginController@logout')->name('logout.admin');
    Route::get('forgot', 'Auth\ForgotPasswordController@index')->name('forgot.admin');
    Route::get('reset-password/{token}', 'Auth\ForgotPasswordController@formForgot')->name('formRequest.admin');
    Route::put('forgot', 'Auth\ForgotPasswordController@sendMailWithToken')->name('sendMailWithToken.forgot.admin');
    Route::post('forgot/{token}', 'Auth\ForgotPasswordController@changePassword')->name('changePassword.forgot.admin');

    Route::group(['as' => 'admin.','middleware' => 'auth.admin',  'namespace' => 'Admin'], function () {
        // Route::get('/', function () {

        //     return view('admin.dashboard.index');
        // })->name('dashboard');
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::resource('/manage', 'AdminController')->middleware('check_role:supper_admin');
        Route::get('/manage-list', 'AdminController@list')->name('manage.list')->middleware('check_role:supper_admin');
        Route::post('/manage/avatar/{id}', 'AdminController@addAvatar')->name('manage.avatar')->middleware('check_role:supper_admin');
        Route::post('/manage-change/{id}', 'AdminController@changePassword')->name('manage.change')->middleware('check_role:supper_admin');

        /* Bộ môn */
        Route::resource('/bomon', 'BoMonController')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::get('/bomon-list', 'BoMonController@list')->name('bomon.list')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');

        /* Môn Học */
        Route::resource('/monhoc', 'MonHocController')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::get('/monhoc-list', 'MonHocController@list')->name('monhoc.list')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');

        /* Giáo viên */
        Route::resource('/giaovien', 'GiaoVienController')->middleware('check_role:supper_admin,admin,quan_ly');
        Route::get('/giaovien-list', 'GiaoVienController@list')->name('giaovien.list')->middleware('check_role:supper_admin,quan_ly');
        Route::get('/giaovien/excel/get', 'GiaoVienController@excel')->name('giaovien.excel')->middleware('check_role:supper_admin,quan_ly');

        /* Chức vụ */
        Route::resource('/chucvu', 'ChucVuController')->middleware('check_role:supper_admin,admin,quan_ly');
        Route::get('/chucvu-list', 'ChucVuController@list')->name('chucvu.list')->middleware('check_role:supper_admin,quan_ly');

        /* Hệ phai */
        Route::resource('/hephai', 'HePhaiController')->middleware('check_role:supper_admin,admin,quan_ly');
        Route::get('/hephai-list', 'HePhaiController@list')->name('hephai.list')->middleware('check_role:supper_admin,quan_ly');

        /* Lớp Học */
        Route::resource('/lophoc', 'LopHocController')->middleware('check_role:supper_admin,dao_tao,quan_ly');
        Route::get('/lophoc-list', 'LopHocController@list')->name('lophoc.list')->middleware('check_role:supper_admin,dao_tao,quan_ly');
        Route::post('/lophoc/filter', 'LopHocController@filter')->name('lophoc.filter')->middleware('check_role:supper_admin,dao_tao,quan_ly');
        Route::get('/lophoc/hocvien/add/{id}', 'LopHocController@create')->name('lophoc.hocvien.create')->middleware('check_role:supper_admin,dao_tao,quan_ly');
        Route::get('/lophoc/tkb/{id}', 'LopHocController@lopThoiKhoaBieu')->name('lophoc.tkb')->middleware('check_role:supper_admin,dao_tao,quan_ly');
        Route::get('/lophoc/tkb/list/{id}', 'LopHocController@listThoiKhoaBieu')->name('lophoc.tkb.list')->middleware('check_role:supper_admin,dao_tao,quan_ly');
        Route::get('/lophoc/diemdanh/list', 'LopHocController@listLopDiemDanh')->name('lophoc.diemdanh')->middleware('check_role:supper_admin,quan_ly,hanh_chinh,dao_tao');
        Route::get('/lophoc/{id}/diemdanh/create', 'LopHocController@lophocDiemDanh')->name('lophoc.diemdanh.create')->middleware('check_role:supper_admin,quan_ly,hanh_chinh,dao_tao');
        Route::get('/lophoc/{id}/diemdanh/create/ngay', 'LopHocController@lophocDiemDanhDetail')->name('lophoc.diemdanh.create.detail')->middleware('check_role:supper_admin,quan_ly,hanh_chinh,dao_tao');
        Route::post('/lophoc/list/diemdanh', 'LopHocController@listDiemDanh')->name('lophoc.diemdanh.list')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::get('/lophoc/diemdanh/show/{id}/{lophoc}', 'LopHocController@showDiemDanh')->name('lophoc.diemdanh.show')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::get('/lophoc/diem/list', 'LopHocController@listLopDiem')->name('lophoc.diem')->middleware('check_role:supper_admin,quan_ly');
        Route::post('/lophoc/diem/store', 'LopHocController@storeDiem')->name('lophoc.diem.store')->middleware('check_role:supper_admin,quan_ly');
        Route::get('/lophoc/diem/create/{id}', 'LopHocController@lopHocDiem')->name('lophoc.diem.create')->middleware('check_role:supper_admin,quan_ly');

        Route::post('/lophoc/diem/lydo', 'LopHocController@monHocDiemLyDo')->name('lophoc.diem.lydo')->middleware('check_role:supper_admin,quan_ly');
        Route::post('/lophoc/monhoc/diemdanh', 'LopHocController@monHocDiemDanhPost')->name('lophoc.monhoc.diemdanh.post')->middleware('check_role:supper_admin,quan_ly');
        Route::post('/lophoc/monhoc/{id}', 'LopHocController@lopMonHoc')->name('lophoc.monhoc')->middleware('check_role:supper_admin,quan_ly');
        Route::post('/lophoc/hocvien/{id}', 'LopHocController@lopHocVien')->name('lophoc.hocvien')->middleware('check_role:supper_admin,quan_ly');
        Route::get('/lophoc/json/{id}', 'LopHocController@editJson')->name('lophoc.json')->middleware('check_role:supper_admin,quan_ly');
        Route::get('/lophoc/all/export', 'LopHocController@export')->name('lophoc.export')->middleware('check_role:supper_admin,quan_ly');
        Route::get('/lophoc/export/{id}', 'LopHocController@exportDetail')->name('lophoc.export.detail')->middleware('check_role:supper_admin,quan_ly');

        /* Lớp Học */
        Route::resource('/lydo', 'LyDoDiemController')->middleware('check_role:supper_admin,dao_tao,quan_ly');
        Route::get('/lydo-list', 'LyDoDiemController@list')->name('lydo.list')->middleware('check_role:supper_admin,dao_tao,quan_ly');

        /* Thời khoá biểu */
        Route::resource('/thoi-khoa-bieu', 'ThoiKhoaBieuController')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::post('/thoi-khoa-bieu/lop-mon-hoc', 'ThoiKhoaBieuController@lopMonHoc')->name('thoi-khoa-bieu.lopmonhoc')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::get('/thoi-khoa-bieu/index/{lophoc}', 'ThoiKhoaBieuController@index')->name('thoi-khoa-bieu.index')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::get('/thoi-khoa-bieu/all/lophoc', 'ThoiKhoaBieuController@indexLopHoc')->name('thoi-khoa-bieu.all.lophoc')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::post('/thoi-khoa-bieu/get/lophoc', 'ThoiKhoaBieuController@lopHoc')->name('thoi-khoa-bieu.lophoc')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');

        /* Học Viên */
        Route::resource('/hoc-vien', 'HocVienController')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien-list', 'HocVienController@list')->name('hoc-vien.list')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien/list2', 'HocVienController@listCalander')->name('hoc-vien.list.calandar')->middleware('check_role:supper_admin');
        Route::post('/hoc-vien/import', 'HocVienController@import')->name('hoc-vien.import')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien/all/export', 'HocVienController@export')->name('hoc-vien.export')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        
        /* chỉnh sửa lại route view import học viên */
        Route::get('/hv-import', 'HocVienController@importView')->name('hoc-vien.importView')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        /* ------------------- */

        Route::get('/hoc-vien/theodoiyte/{id}', 'HocVienController@theoDoiYTe')->name('hoc-vien.theo-doi-y-te')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien/vephep/{id}', 'HocVienController@vePhep')->name('hoc-vien.ve-phep')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
       
        Route::get('/hoc-vien/taichinh/filter/{id}', 'HocVienController@filterTaiChinh')->name('hoc-vien.taichinh.filter')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien/anhquatrinh/{id}', 'HocVienController@indexAnhQuaTrinh')->name('hoc-vien.anhquatrinh.index')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::post('/hoc-vien/anhquatrinh', 'HocVienController@themAnhQuaTrinh')->name('hoc-vien.anhquatrinh.post')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien/diem/export/{id}', 'HocVienController@exportDiem')->name('hoc-vien.diem.export')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');

app/Models/GiaoVien.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class GiaoVien extends Model
{
    protected $table = 'giao_viens';

    protected $fillable = [
        'ten', 
        'email', 
        'he_phai_id',
        'chuc_vu_id', 
        'quoc_gia', 
        'ngay_sinh', 
        'doi_tac', 
        'so_dien_thoai', 
        'anh_dai_dien', 
        'nguoi_gioi_thieu', 
        'ghi_chu', 
    ];
 

    public function LopHoc()
    {
        return $this->hasMany('App\Models\LopHoc');
    }
   
    public function chucvu()
    {
        return $this->belongsTo('App\Models\ChucVu','chuc_vu_id');
    }

    public function hephai()
    {
        return $this->belongsTo('App\Models\HePhai','he_phai_id');
    }

}

app/Http/Controllers/Admin/GiaoVienController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\Admin\GiaoVienService;
use App\Models\MonHoc;
use App\Models\GiaoVien;
use App\Models\HePhai;
use App\Models\ChucVu;
use App\Http\Requests\Admin\GiaoVienRequest;
use App\Exports\GiaoVienExport;
use Maatwebsite\Excel\Facades\Excel;
use Exception;
use Session;
use Storage;

class GiaoVienController extends Controller
{

    protected $giaovienService;

    public function __construct(GiaoVienService $giaovienService)
    {
        $this->giaovienService = $giaovienService;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.giaovien.index');        
    }

    public function list(Request $request)
    {
        $listGiaoVien = $this->giaovienService->getListGiaoVien($request->all());
        return $listGiaoVien;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $hephais = HePhai::all();
        $chucvus = ChucVu::all();
        $nationJson = file_get_contents("nation.json");  
        $nations = json_decode($nationJson, true);

        return view('admin.giaovien.addnew',compact('hephais','chucvus','nations'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(GiaoVienRequest $request)
    {
        $result = $this->giaovienService->store($request);

        if ($result) {
            Session::flash('message', trans('Thêm thành công ! '));

            return redirect()->route('admin.giaovien.index')->with('message', 'Thêm thành công');
        }

        Session::flash('error', trans('Thêm thất bại !'));

        return redirect()->route('admin.giaovien.index')->with('message', 'thêm thất bại');;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $giaovien = $this->giaovienService->find($id);
        return view('admin.giaovien.detail',compact('giaovien'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $giaovien = $this->giaovienService->find($id);
        $hephais = HePhai::all();
        $chucvus = ChucVu::all();
        return view('admin.giaovien.edit',compact('giaovien','hephais','chucvus'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(GiaoVienRequest $request, $id)
    {
        $result = $this->giaovienService->updateGiaoVien($request,$id);

        if ($result) {
            Session::flash('message', trans('Thêm thành công ! '));
            return redirect()->route('admin.giaovien.index')->with('message', 'cập nhật môn học thành công');
        }

        Session::flash('error', trans('Thêm thất bại !'));
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $this->giaovienService->delete($id);
            return redirect()->route('admin.giaovien.index')->with('message', 'Xóa thành công');
        }catch (Exception $e) {
            report($e);
            return redirect()->route('admin.giaovien.index')->with('error', 'Xóa không thành công');
        }
    }

    public function excel(){
        return Excel::download(new GiaoVienExport(),'Danh Sách Giáo Viên.xlsx');
    }
}

resources/views/admin/giaovien/addnew.blade.php
@extends('admin.layouts.index')
@section('content')
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h4>Thêm thông tin giáo viên </h4>
				</div><!-- /.col -->
				<div class="col-sm-6">
					<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item"><a href="/">Home</a></li>
						<li class="breadcrumb-item active"> Thêm thông tin giáo viên</li>
					</ol>
				</div> 
			</div><!-- /.row -->
		</div><!-- /.container-fluid -->
	</section>
	<!-- /.content-header -->
	<!-- Main content -->
	<section class="content">
		<div class="container-fluid">
			<!-- Small boxes (Stat box) -->
			<div class="row">
				<div class="col-lg-12 mb-4">
					<a  href="{{ URL::previous() }}" class="btn btn-default"><i class="fas fa-undo"></i> Trở về</a>
				</div>
				<!-- ./col -->
				<div class="col-lg-12">
					<form action="{{ route('admin.giaovien.store') }} " 
						method="post" id="create_giaovien" role="form" 
						data-url-index="{{ route('admin.giaovien.index') }}"
						enctype="multipart/form-data"
					>
						@csrf
						<input name="_method" type="hidden" value="POST">
						<div class="row">
							<div class="col-lg-12">
								<div class="card card-success card-outline">
									<div class="card-header">
										<h3 class="card-title"><i class="far fa-user"></i> Thông tin cá nhân</h3>
									</div>
									<!-- /.card-header -->
									<div class="card-body">     
										<div class="row">
											<!-- ./ col   -->
											<div class="col-md-12">
												<div class="show-fileiamge text-center d-none">
													<img class="img-responsive profile-user-img img-fluid img-circle cus-avatar"
														id="avatar"
														src="">
												</div>
												<div class="form-group file-upload m-auto">
													<label class="input-file-trigger" for="fileupload"><i class="fas fa-file-upload"></i> Tải ảnh giáo viên <span class="text-danger">*</span></label>
													<input type="file" class="form-control input-file" id="fileupload" placeholder="" name="anh_dai_dien">
													<span class="text-danger anh_dai_dien" role="alert"></span>
												</div>
											</div>
											<div class="col-md-4 col-12">
												<div class="form-group">
													<label>Họ & tên <span class="text-danger">*</span></label>
													<input type="text" class="form-control text-capitalize" name="ten" id="ipname" value="{{old('ten')}}" placeholder="Họ và tên giáo viên" >
													@error('ten')
														<span class="text-danger ten" role="alert">{{ $message }}</span>
													@enderror
												</div>
											</div>
											<div class="col-md-4 col-12">
												<div class="form-group">
													<label>Email <span class="text-danger">*</span></label>
													<input type="email" class="form-control" name="email" value="{{old('email')}}" placeholder="Email">
													@error('email')
														<span class="text-danger email" role="alert">{{ $message }}</span>
													@enderror
												</div>
											</div>
											<div class="col-md-4 col-12">
												<div class="form-group">
													<label>Quốc gia</label>
													<select id="country" name="quoc_gia" class="form-control">
													@foreach($nations as $nation )
														<option value="{{$nation['name']}}">{{$nation['name']}}</option>
													@endforeach
													</select>
													<span class="text-danger quoc_gia" role="alert"></span>
												</div>
											</div>
											<div class="col-md-4 col-12">
												<div class="form-group">
													<label>Ngày sinh <span class="text-danger">*</span></label>
													<input type="date" class="form-control" name="ngay_sinh" value="{{old('ngay_sinh')}}"  placeholder="Ngày sinh" >
													@error('ngay_sinh')
														<span class="text-danger ngay_sinh" role="alert">{{ $message }}</span>
													@enderror
												</div>
											</div>
											<div class="col-md-4">
												<div class="form-group">
													<label>Chức vụ <span class="text-danger">*</span></label>
													<select name="chuc_vu_id" class="form-control">
													@foreach($chucvus as $chucvu)
														<option value="{{$chucvu->id}}">{{$chucvu->ten}}</option>
													@endforeach
													</select>
													@error('chuc_vu_id')
															<span class="text-danger chuc_vu_id" role="alert">{{ $message }}</span>
													@enderror
												</div>
											</div>
											<div class="col-md-4">
												<div class="form-group">
													<label>Số điện thoại <span class="text-danger">*</span></label>
													<input type="number" class="form-control" value="{{old('so_dien_thoai')}}"  placeholder="Số điện thoại" name="so_dien_thoai" id="reservation">
													@error('so_dien_thoai')
															<span class="text-danger so_dien_thoai" role="alert">{{ $message }}</span>
													@enderror
												</div>
											</div>
											<div class="col-md-4">
												<div class="form-group">
													<label>Đối tác</label>
													<select name="doi_tac" class="form-control">
														<option value="Lâu Dài">Lâu Dài</option>
														<option value="Ngắn Hạn">Ngắn Hạn</option>
														<option value="Định Kỳ">Định Kỳ</option>
													</select>
													@error('doi_tac')
														<span class="text-danger doi_tac" role="alert">{{ $message }}</span>
													@enderror
												</div>
											</div>
											<div class="col-md-4">
												<div class="form-group">
													<label>Hệ phái <span class="text-danger">*</span></label>
													<select name="he_phai_id" class="form-control">
													@foreach($hephais as $hephai)
													<option value="{{$hephai->id}}">{{$hephai->ten}}</option>
													@endforeach
													</select>
													@error('he_phai_id')
													<span class="text-danger he_phai_id" role="alert">{{ $message }}</span>
													@enderror
												</div>
											</div>
											<div class="col-md-4">
												<div class="form-group">
													<label>Người giới thiệu </label>
													<input type="text" class="form-control text-capitalize" value="{{old('nguoi_gioi_thieu')}}"  placeholder="Người giới thiệu" name="nguoi_gioi_thieu" id="">
													<span class="text-danger nguoi_gioi_thieu" role="alert"></span>
												</div>
											</div>
											<div class="col-md-12">
												<div class="form-group">
													<label>Ghi chú</label>
													<input type="text" class="form-control" value="{{old('ghi_chu')}}"  placeholder="Ghi chú" name="ghi_chu" id="">
													<span class="text-danger ghi_chu" role="alert"></span>
												</div>
											</div>
										</div>
										
									</div>
									<!-- /.card-body -->
								</div>
								<!-- thong tin ca nhan -->
							</div>
							<div class="col-lg-12 mb-4 text-right">
								<a href="/giaovien" class="btn btn-default mr-2"><i class="fas fa-times"></i> Huỷ bỏ</a>
								<button type="submit" class="btn btn-info"><i class="fas fa-save"></i> Lưu thông tin</button>
							</div>
						</div>
					</form>
				</div>
				<!-- ./col -->
			</div>
			<!-- /.row -->
		</div><!-- /.container-fluid -->
	</section>
	<!-- /.content -->
@endsection
@section('scripts')
  {{ Html::script(mix('admin/giaovien.js')) }}
@endsection

resources/views/admin/giaovien/index.blade.php
@extends('admin.layouts.index')
@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h4>Danh sách giáo viên </h4>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active"> Giáo viên</li>
                    </ol>
                </div> 
                <div class="col-12 mt-2">
                    <a href="{{route('admin.giaovien.create')}}" class="btn btn-success">
                        <i class="fas fa-user-plus"></i> Thêm giáo viên
                    </a>
                </div>
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content-header -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h3 class="card-title flex-grow-1"><i class="fas fa-users"></i> Danh sách giáo viên</h3>
                        <div class="dt-buttons btn-group flex-wrap">
                            <a href="{{route('admin.giaovien.excel')}}" class="btn btn-success"  type="button"><span><i class="far fa-file-excel"></i> Xuất file Excel</span></a>  
                        </div>
                    </div>
                    <div class="card-body">
                        <div id="table_wrapper" class="cus_tb dataTables_wrapper dt-bootstrap4">
                            <table id="table_gv" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>Stt</th>
                                        <th>Tên</th>
                                        <th>Email</th>
                                        <th>Số điện thoại</th>
                                        <th>Ngày sinh</th>
                                        <th>Hệ phái</th>
                                        <th width="20%">Tác vụ</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>                  
            </div>
        </div>
        {{ Form::open(['route' => ['admin.giaovien.destroy', 'ID_REPLY_IN_URL'], 'id' => 'delete-giaovien-form', 'class' => 'form-horizontal']) }}
            {{ method_field('DELETE') }}
        {{ Form::close() }}      
    </section>

    <div class="mess-data"
        data-url-datatable="{{ route('admin.giaovien.list') }}"
        data-url-edit="{{ route('admin.giaovien.edit', 'ID_REPLY_IN_URL') }}"
        data-url-show="{{ route('admin.giaovien.show', 'ID_REPLY_IN_URL') }}"
        data-url-delete="{{ route('admin.giaovien.destroy', 'ID_REPLY_IN_URL') }}"
        >
    </div>

    @component('admin.components.modals.alert-delete')
        @slot('headerText')
            {{ "Bạn có muốn xóa giáo viên" }}
        @endslot
    @endcomponent
@endsection
@section('scripts')
    {{ Html::script(mix('admin/giaovien.js')) }}
@endsection