routes/web.php
        Route::post('/lophoc/diem/lydo', 'LopHocController@monHocDiemLyDo')->name('lophoc.diem.lydo')->middleware('check_role:supper_admin,quan_ly');
        Route::post('/lophoc/monhoc/diemdanh', 'LopHocController@monHocDiemDanhPost')->name('lophoc.monhoc.diemdanh.post')->middleware('check_role:supper_admin,quan_ly');
        Route::post('/lophoc/monhoc/{id}', 'LopHocController@lopMonHoc')->name('lophoc.monhoc')->middleware('check_role:supper_admin,quan_ly');
        Route::post('/lophoc/hocvien/{id}', 'LopHocController@lopHocVien')->name('lophoc.hocvien')->middleware('check_role:supper_admin,quan_ly');
        Route::get('/lophoc/json/{id}', 'LopHocController@editJson')->name('lophoc.json')->middleware('check_role:supper_admin,quan_ly');
        Route::get('/lophoc/all/export', 'LopHocController@export')->name('lophoc.export')->middleware('check_role:supper_admin,quan_ly');
        Route::get('/lophoc/export/{id}', 'LopHocController@exportDetail')->name('lophoc.export.detail')->middleware('check_role:supper_admin,quan_ly');

        /* Lớp Học */
        Route::resource('/lydo', 'LyDoDiemController')->middleware('check_role:supper_admin,dao_tao,quan_ly');
        Route::get('/lydo-list', 'LyDoDiemController@list')->name('lydo.list')->middleware('check_role:supper_admin,dao_tao,quan_ly');

        /* Thời khoá biểu */
        Route::resource('/thoi-khoa-bieu', 'ThoiKhoaBieuController')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::post('/thoi-khoa-bieu/lop-mon-hoc', 'ThoiKhoaBieuController@lopMonHoc')->name('thoi-khoa-bieu.lopmonhoc')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::get('/thoi-khoa-bieu/index/{lophoc}', 'ThoiKhoaBieuController@index')->name('thoi-khoa-bieu.index')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::get('/thoi-khoa-bieu/all/lophoc', 'ThoiKhoaBieuController@indexLopHoc')->name('thoi-khoa-bieu.all.lophoc')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');
        Route::post('/thoi-khoa-bieu/get/lophoc', 'ThoiKhoaBieuController@lopHoc')->name('thoi-khoa-bieu.lophoc')->middleware('check_role:supper_admin,quan_ly,dao_tao,hanh_chinh');

        /* Học Viên */
        Route::resource('/hoc-vien', 'HocVienController')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien-list', 'HocVienController@list')->name('hoc-vien.list')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien/list2', 'HocVienController@listCalander')->name('hoc-vien.list.calandar')->middleware('check_role:supper_admin');
        Route::post('/hoc-vien/import', 'HocVienController@import')->name('hoc-vien.import')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien/all/export', 'HocVienController@export')->name('hoc-vien.export')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        
        /* chỉnh sửa lại route view import học viên */
        Route::get('/hv-import', 'HocVienController@importView')->name('hoc-vien.importView')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        /* ------------------- */

        Route::get('/hoc-vien/theodoiyte/{id}', 'HocVienController@theoDoiYTe')->name('hoc-vien.theo-doi-y-te')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien/vephep/{id}', 'HocVienController@vePhep')->name('hoc-vien.ve-phep')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
       
        Route::get('/hoc-vien/taichinh/filter/{id}', 'HocVienController@filterTaiChinh')->name('hoc-vien.taichinh.filter')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien/anhquatrinh/{id}', 'HocVienController@indexAnhQuaTrinh')->name('hoc-vien.anhquatrinh.index')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::post('/hoc-vien/anhquatrinh', 'HocVienController@themAnhQuaTrinh')->name('hoc-vien.anhquatrinh.post')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien/diem/export/{id}', 'HocVienController@exportDiem')->name('hoc-vien.diem.export')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/hoc-vien/diemdanh/export/{id}', 'HocVienController@exportDiemDanh')->name('hoc-vien.diemdanh.export')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');

        /* Về phép */
        Route::resource('ve-phep', 'VePhepController')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/ve-phep-list/{id}', 'VePhepController@list')->name('ve-phep.list')->middleware('check_role:supper_admin,hanh_chinh,quan_ly');

        /* Phòng */
        Route::resource('phong', 'PhongController')->middleware('check_role:supper_admin,admin,quan_ly');
        Route::get('phong-list', 'PhongController@list')->name('phong.list')->middleware('check_role:supper_admin,admin,quan_ly');
        Route::get('phong/create-hv/{id}', 'PhongController@createHocVien')->name('phong.create.hv')->middleware('check_role:supper_admin,admin,quan_ly');
        Route::post('phong/create-hv', 'PhongController@postHocVien')->name('phong.post.hv')->middleware('check_role:supper_admin,admin,quan_ly');
        Route::post('phong/add-hv', 'PhongController@hocvienAll')->name('phong.add.hv')->middleware('check_role:supper_admin,admin,quan_ly');
        Route::post('phong/chuyen-phong', 'PhongController@chuyenPhong')->name('phong.chuyenphong')->middleware('check_role:supper_admin');
        Route::get('phong/add_truong_phong/{id}', 'PhongController@show')->name('phong.truongphong.create')->middleware('check_role:supper_admin,admin,quan_ly');
        Route::post('phong/add_truong_phong', 'PhongController@storeTruongPhong')->name('phong.truongphong')->middleware('check_role:supper_admin,admin,quan_ly');
        Route::get('phong/show_hocvien/{id}', 'PhongController@showHocVien')->name('phong.show.hocvien')->middleware('check_role:supper_admin,admin,quan_ly');
        Route::get('/phong/export/{id}', 'PhongController@export')->name('phong.export')->middleware('check_role:supper_admin,admin,quan_ly');
     
         /* Diễm giải tài chính*/
        Route::resource('diengiai-taichinh', 'DienGiaiTaiChinhController')->middleware('check_role:supper_admin,quan_ly,tai_chinh');
        Route::get('/diengiai-taichinh-list', 'DienGiaiTaiChinhController@list')->name('diengiai-taichinh.list')->middleware('check_role:supper_admin,quan_ly,tai_chinh');

          /* Tài chính */
        Route::resource('/taichinh', 'TaiChinhController')->middleware('check_role:supper_admin,quan_ly,tai_chinh');
        Route::get('/taichinh/filter/{id}', 'TaiChinhController@filterMonth')->name('taichinh.filter')->middleware('check_role:supper_admin,quan_ly,tai_chinh');
        Route::get('/taichinh/export/{id}', 'TaiChinhController@export')->name('taichinh.export')->middleware('check_role:supper_admin,quan_ly,tai_chinh');

         /* Hạnh kiểm */
        Route::resource('hanhkiem', 'HanhKiemController')->middleware('check_role:supper_admin,dao_tao,quan_ly');
        Route::get('/hanhkiem-list', 'HanhKiemController@list')->name('hanhkiem.list')->middleware('check_role:supper_admin,dao_tao,quan_ly');

          /* Nhóm */
        Route::resource('/nhom', 'NhomController')->middleware('check_role:supper_admin,admin,dao_tao,quan_ly');
        Route::get('/nhom-list', 'NhomController@list')->name('nhom.list')->middleware('check_role:supper_admin,admin,dao_tao,quan_ly');
        Route::resource('/nhomcha', 'NhomChaController')->middleware('check_role:supper_admin,admin,dao_tao,quan_ly');
        Route::get('/nhomcha-list', 'NhomChaController@list')->name('nhomcha.list')->middleware('check_role:supper_admin,admin,dao_tao,quan_ly');
        Route::get('/nhom-hocvien/{id}', 'NhomController@nhomHocVien')->name('nhom.hocvien')->middleware('check_role:supper_admin,admin,dao_tao,quan_ly');
        Route::post('/nhom-hocvien', 'NhomController@nhomHocVienPost')->name('nhom.hocvien.post')->middleware('check_role:supper_admin,admin,dao_tao,quan_ly');
        Route::get('/nhom-hocvien-list/{id}', 'NhomController@nhomHocVienList')->name('nhom.hocvien.list')->middleware('check_role:supper_admin,admin,dao_tao,quan_ly');
        Route::get('/nhom-hocvien-export/{id}', 'NhomController@nhomHocVienExport')->name('nhom.hocvien.export')->middleware('check_role:supper_admin,admin,dao_tao,quan_ly');

          /* Kỷ luật */
        Route::resource('kyluat', 'KyLuatController',
        array('names' => array('create' => 'create/{id}')))->middleware('check_role:supper_admin,admin,dao_tao,quan_ly');
        Route::get('/kyluat-list', 'KyLuatController@list')->name('kyluat.list')->middleware('check_role:supper_admin,admin,dao_tao,quan_ly');
        Route::get('kyluat/create/{id}', 'KyLuatController@create')->name('kyluat.created')->middleware('check_role:supper_admin,admin,dao_tao,quan_ly');

        /* Khám Sức Khoẻ */
        Route::resource('khamsuckhoe', 'KhamSucKhoeController')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('/khamsuckhoe-list', 'KhamSucKhoeController@list')->name('khamsuckhoe.list')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');
        Route::get('khamsuckhoe/create/{id}', 'KhamSucKhoeController@create')->name('khamsuckhoe.created')->middleware('check_role:supper_admin,hanh_chinh,quan_ly');
        Route::get('khamsuckhoe/count/{id}', 'KhamSucKhoeController@count')->name('khamsuckhoe.count')->middleware('check_role:supper_admin,hanh_chinh,quan_ly');
        Route::get('khamsuckhoe/excel/{id}', 'KhamSucKhoeController@excel')->name('khamsuckhoe.excel')->middleware('check_role:supper_admin,hanh_chinh,quan_ly');

        /* Tình Trạng Nghiện */
        Route::resource('tinhtrangnghien', 'TinhTrangNghienController')->middleware('check_role:supper_admin,quan_ly,hanh_chinh');

app/Models/VePhep.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class VePhep extends Model
{
    
    protected $table = 've_pheps';

    protected $fillable = [
        'hoc_vien_id', 
        'tinh_trang', 
        'ngay_ve',
        'ngay_vao',
        'thang_ve',
        'thang_vao',
        'ghi_chu' ,
        'ly_do' ,
    ];
    
    public function hocvien()
    {
        return $this->belongsTo('App\Models\HocVien','hoc_vien_id');
    } 
}

app/Http/Controllers/Admin/VePhepController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\Admin\VePhepService;
use App\Models\VePhep;
use App\Http\Requests\Admin\VePhepRequest;
use Exception;
use Session;
class VePhepController extends Controller
{

    protected $vePhepService;

    public function __construct(VePhepService $vePhepService)
    {
        $this->vePhepService = $vePhepService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    public function list($id)
    {
        $listVePhep = $this->vePhepService->getListVePhep($id);
        return $listVePhep;
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(VePhepRequest $request)
    {
        $request->request->add(['thang_ve' => date("m",strtotime($request->ngay_ve))]);
        if($request->ngay_vao !== NULL){
            $request->request->add(['thang_vao' => date("m",strtotime($request->ngay_vao))]);
        }
        $result = $this->vePhepService->store($request);
        if ($result) {
            Session::flash('message', trans('Thêm thành công ! '));
            return response()->json([
                'status' => true,
            ]);
        }

        Session::flash('error', trans('Thêm thất bại !'));
        return response()->json([
            'status' => false,
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        dd($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $result = $this->vePhepService->update($request->all(),$id);
        if ($result) {
            Session::flash('message', trans('Thêm thành công ! '));
            return response()->json([
                'status' => true,
            ]);
        }
        Session::flash('error', trans('Thêm thất bại !'));
        return response()->json([
            'status' => false,
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $hocvien = $this->vePhepService->find($id);
            $this->vePhepService->delete($id);
            return redirect()->route('admin.hoc-vien.ve-phep',$hocvien->hoc_vien_id)->with('message', 'Xóa thành công');
        } catch (Exception $e) {
            report($e);
            return redirect()->route('admin.hoc-vien.ve-phep',$hocvien->hoc_vien_id)->with('error', 'Xóa không thành công');
        }
    }
}

resources/views/admin/vephep/index.blade.php
@extends('admin.layouts.index')
@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-md-12">
                    <div class="col-12">
                        <a href="javascript:void(0)" class="btn btn-success" data-toggle="modal" data-target="#modal-default">
                            <i class="far fa-calendar-plus"></i> Thêm mới về phép
                        </a>
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title"><i class="fas fa-users"></i> Danh sách về phép - Tên HV : {{$hocvien->ten}} - Mã HV :{{$hocvien->ma_hoc_vien}}</h3>     
                    </div>
                    <div class="card-body">
                        <div id="hv_kyluat_wrapper" class="dataTables_wrapper dt-bootstrap4">
                            <table id="example2" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>Stt</th>
                                        <th>Ngày về</th>
                                        <th>Ngày quay lại</th>
                                        <th>Lý do</th>
                                        <th>Tình trạng</th>
                                        <th>Ghi chú</th>
                                        <th width="10%">Tác vụ</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>                  
            </div>
        </div>
        {{ Form::open(['route' => ['admin.ve-phep.destroy', 'ID_REPLY_IN_URL'], 'id' => 'delete-ve-phep-form', 'class' => 'form-horizontal']) }}
            {{ method_field('DELETE') }}
        {{ Form::close() }}      
    </section>

    <div class="mess-data"
        data-url-datatable="{{ route('admin.ve-phep.list',$hocvien->id) }}"
        data-url-edit="{{ route('admin.ve-phep.update', 'ID_REPLY_IN_URL') }}"
        data-url-show="{{ route('admin.ve-phep.show', 'ID_REPLY_IN_URL') }}"
        data-url-delete="{{ route('admin.ve-phep.destroy', 'ID_REPLY_IN_URL') }}">
        
    </div>

    @component('admin.components.modals.alert-delete')
        @slot('headerText')
            {{ "Bạn có muốn xóa về phép" }}
        @endslot
    @endcomponent

    @component('admin.components.modals.form-modal')
        @slot('title')
            Về phép học viên
        @endslot
        @slot('form')
        <form action="{{ route('admin.ve-phep.store') }}" id="create_vephep" role="form" method="post" data-url-index="{{ route('admin.hoc-vien.ve-phep',$hocvien->id) }}">
            @csrf
            <input type="hidden" value="{{$hocvien->id}}" name="hoc_vien_id"> 
            <div class="card-body">
                <div class="row">
                    <div class="form-group col-md-6">
                        <label>Ngày về:</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="far fa-calendar-alt"></i>
                                </span>
                            </div>
                                <input type="date" name="ngay_ve" class="form-control float-right">
                        </div>
                        <span class="text-danger ngay_ve" role="alert"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label>Ngày quay lại:</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="far fa-calendar-alt"></i>
                                </span>
                            </div>
                            <input type="date" name="ngay_vao" class="form-control float-right">
                        </div>
                        <span class="text-danger ngay_vao" role="alert"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label>Tình trạng quay lại</label>
                        <input type="text" name="tinh_trang" class="form-control" placeholder="Tình trạng quay lại">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Lý do</label>
                        <select name="ly_do" class="form-control">
                            <option value="0">Xin Về</option>
                            <option value="1">Trốn</option>
                        </select>
                    </div>
                    <div class="form-group col-md-12">
                        <label>Ghi chú</label>
                        <textarea name="ghi_chu" class="form-control" placeholder="Ghi chú"></textarea>
                    </div>
                    
                </div>
            </div>
            <div class="card-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times"></i> Hủy bỏ</button>
                <button type="submit" class="btn btn-success float-right"><i class="fas fa-save"></i> Lưu thông tin</button>
            </div>
        </form>
        @endslot
    @endcomponent

    @component('admin.components.modals.edit-modal')
        @slot('title')
            Cập nhật thông tin về phép của học viên
        @endslot
        @slot('form')
        <form action="" id="update_vephep" role="form" method="put" data-url-index="{{ route('admin.hoc-vien.ve-phep',$hocvien->id) }}">
            @csrf
            @method('PUT')
            <input type="hidden" value="{{$hocvien->id}}" name="hoc_vien_id"> 
            <div class="card-body">
                <div class="row">
                    <div class="form-group col-md-6">
                        <label>Ngày về:</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="far fa-calendar-alt"></i>
                                </span>
                            </div>
                                <input type="date" name="ngay_ve" class="form-control float-right">
                        </div>
                        <span class="text-danger ngay_ve" role="alert"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label>Ngày quay lại:</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="far fa-calendar-alt"></i>
                                </span>
                            </div>
                            <input type="date" name="ngay_vao" class="form-control float-right">
                        </div>
                        <span class="text-danger ngay_vao" role="alert"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label>Tình trạng quay lại</label>
                        <input type="text" name="tinh_trang" class="form-control" placeholder="Tình trạng quay lại">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Lý do</label>
                        <select name="ly_do" class="form-control">
                            <option value="0">Xin Về</option>
                            <option value="1">Trốn</option>
                        </select>
                    </div>
                    <div class="form-group col-md-12">
                        <label>Ghi chú</label>
                        <textarea name="ghi_chu" class="form-control" placeholder="Ghi chú"></textarea>
                    </div>
                    
                </div>
            </div>
            <div class="card-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times"></i> Hủy bỏ</button>
                <button type="submit" class="btn btn-success float-right"><i class="fas fa-save"></i> Lưu thông tin</button>
            </div>
        </form>
        @endslot
    @endcomponent
   
@endsection
@section('scripts')
    <script>
        $(function() {
            
        });
    </script>
    {{ Html::script(mix('admin/vephep.js')) }}
@endsection